AllCops:
  TargetRubyVersion: 2.6.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/**/*'
    - 'lib/tasks/*'
    - vendor/**/*
    - config/routes.rb
    - config/puma.rb
    - config/environments/

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'spec/**/*'

Style/BlockComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
