export const API_CALL_BEGIN = "API_CALL_BEGIN";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const GET_MEALS = "GET_MEALS";
export const GET_MEALS_SUCCESS = "GET_MEALS_SUCCESS";
export const GET_MEALS_FAILURE = "GET_MEALS_FAILURE";

export const GET_MEAL = "GET_MEAL";
export const GET_MEAL_SUCCESS = "GET_MEAL_SUCCESS";
export const GET_MEAL_FAILURE = "GET_MEAL_FAILURE";

export const CREATE_MEAL = "CREATE_MEAL";
export const CREATE_MEAL_SUCCESS = "CREATE_MEAL_SUCCESS";
export const CREATE_MEAL_FAILURE = "CREATE_MEAL_FAILURE";

export const UPDATE_MEAL = "UPDATE_MEAL";
export const UPDATE_MEAL_SUCCESS = "UPDATE_MEAL_SUCCESS";
export const UPDATE_MEAL_FAILURE = "UPDATE_MEAL_FAILURE";

export const DELETE_MEAL = "DELETE_MEAL";
export const DELETE_MEAL_SUCCESS = "DELETE_MEAL_SUCCESS";
export const DELETE_MEAL_FAILURE = "DELETE_MEAL_FAILURE";

export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const SET_SELECTED_MEAL = "SET_SELECTED_MEAL";
export const SET_SELECTED_USER = "SET_SELECTED_USER";

export const RESET_SELECTED_MEAL = "RESET_SELECTED_MEAL";
export const RESET_SELECTED_USER = "RESET_SELECTED_USER";

export const POPULATE_USER = 'POPULATE_USER';

export const FILTER_MEALS = 'FILTER_MEALS';
export const CLEAR_FILTER = 'CLEAR_FILTER';

export const UPDATE_CURRENT_USER_CALORIES = 'UPDATE_CURRENT_USER_CALORIES';

export const SET_FILTER_START_DATE = 'SET_FILTER_START_DATE';
export const SET_FILTER_END_DATE = 'SET_FILTER_END_DATE';
export const SET_FILTER_START_TIME = 'SET_FILTER_START_TIME';
export const SET_FILTER_END_TIME = 'SET_FILTER_END_TIME';
